# This is a basic workflow that is automatically triggered

name: Build and Release Solution 

# Controls when the action will run. Workflow runs when push or pull to main  branch

on:
  push:
    branches:
      - main

env:
  OPENSAL_BUILD_DIR: ${{ github.workspace }}\build\
  __your_choice: 8
  MY_WORKFLOW_VAR: work

jobs:
  build:
    runs-on: windows-latest
    env: 
      RELEASE_TAG: ${{ github.ref_name }}
      GITHUB_CONTEXT: ${{ toJson(github) }}
      GITHUB_SHA: ${{ github.sha }}
      
    defaults:
      run:
        shell: pwsh

    steps:
      - name: SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6        

      - name: SHA-OUT
        run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: echo MSBuild
        run: msbuild -version          
        
      - name: Build
        run: |
          cd ${{ github.workspace }}\src\vcxproj
          .\rebuild.cmd
          
#      - name: Populate build
#        run: |
#          cd ${{ github.workspace }}\src\vcxproj
#          .\!populate_build_dir.cmd
      
      - name: Zip artifact for deployment
#        run: Compress-Archive -Path ${{ github.workspace }}\* -Destination release.zip
        run: |
          powershell Compress-Archive -Path ${{ github.workspace }}\* -DestinationPath release.zip        

      - name: "Create release"
        id: create_release
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG + '_' + process.env.SHA,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG + '_' + process.env.SHA,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

#      - name: Upload Release
#        uses: ncipollo/release-action@v1.12.0
#        with:
#          artifacts: "release.zip"
#          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
          upload_url: ${{env.RELEASE_UPLOAD_URL}}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
