# This is a basic workflow that is automatically triggered

name: Build Solution

# Controls when the action will run. Workflow runs when push or pull to main  branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  OPENSAL_BUILD_DIR: ${{ github.workspace }}\build\
  __your_choice: 8

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: echo MSBuild
        run: msbuild -version          
        
      - name: Build
        run: |
          cd ${{ github.workspace }}\src\vcxproj
          .\rebuild.cmd
          
#      - name: Populate build
#        run: |
#          cd ${{ github.workspace }}\src\vcxproj
#          .\!populate_build_dir.cmd
          
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: upload windows artifact   
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/salamander.windows-amd64.zip
          asset_name: salamander.windows-amd64.zip
          asset_content_type: application/zip          
      
#      - name: Create release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          tag: ${{ github.ref_name }}
#        run: |
#          gh release create "$tag" \
#              --repo="$GITHUB_REPOSITORY" \
#              --title="${tag#v}" \
#              --generate-notes
